### ISSUE TITLE
weekly run fails on 'Registered client is invalid or expired'

### ISSUE THREAD

**Issue by stijnvanhoey** [fluves/pywaterinfo#45]
```
pywaterinfo.waterinfo.KiwisException: Waterinfo call returned 403 errorwith the message b'<?xml version="1.0" ?><ExceptionReport><Exception exceptionCode="AuthInvalid"><ExceptionText>Registered client is invalid or expired.</ExceptionText></Exception></ExceptionReport>'
```

@binomaiheu any idea what is happening?

**Comment by binomaiheu** [comment]
Strange, I just had a look manually using the pywaterinfo token and I can get an authorization token with which I can query the API. Hmm, does the issue persist still ? Will poke some people...

**Comment by stijnvanhoey** [comment]
Thanks!

> does the issue persist still

I restarted the runs, so we can check.

**Comment by binomaiheu** [comment]
Ah, the issue is for the HIC token apparently.

**Comment by stijnvanhoey** [comment]
> the issue is for the HIC token apparently

sorry, my mistake. I'll contact HIC.

**Comment by stijnvanhoey** [comment]
so far I had no response from HIC about the status of the token.

**Comment by stijnvanhoey** [comment]
token has been renewed by hic, closing this issue.
