### ISSUE TITLE
http proxy support

### ISSUE THREAD

**Issue by stijnvanlooy** [fluves/pywaterinfo#58]
* pywaterinfo version: 0.6.0
* Python version: 3.9.15
* Operating System: Ubuntu 22.04.1 LTS

### Description

I'm using pywaterinfo behind a company http proxy. It would be nice if pywaterinfo supported the proxies configuration as the underlying requests and requests_cache packages do.

### What I Did

I added a proxies argument to the Waterinfo constructor that is then passed to requests.
This solved the issue for me.
But I haven't tested other use cases. Thus some further modifications might be required.
I would be happy to share these (small) code modifications, but it looks like I don't have permission to push new branches to the pywaterinfo repository.

**Comment by stijnvanlooy** [comment]
ow yes: forks! :-) thank you!

Using the environment variables will probably also help. (didn't try)

**Comment by stijnvanhoey** [comment]
@stijnvanlooy Would be great to have your fix integrated, feel free to ask any support to get your code adjustments integrated. It boils down to forking > create PR to upstream (this repo), but certainly willing to support if you bump into issues.

**Comment by stijnvanlooy** [comment]
@stijnvanhoey see #59 
that fix worked in my use case

**Comment by stijnvanhoey** [comment]
Fixed by https://github.com/fluves/pywaterinfo/pull/59, closing.
