### ISSUE TITLE
Pandas Future warning: parsing datetimes with mixed timezones (Pandas updates)

### ISSUE THREAD

**Issue by Jornvdv** [fluves/pywaterinfo#67]
* pywaterinfo version: 0.7.0.post1.dev7+g25502b8 (based on [this](https://github.com/fluves/pywaterinfo/pull/63) pull request)
* Python version: 3.10.14
* Operating System: Windows
* Pandas version: 2.2.2

### Description

While using pywaterinfo, I got this FutureWarning, related to Pandas and its timeseries handling: _{env location}lib\site-packages\pywaterinfo\waterinfo.py:644: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df["Timestamp"] = pd.to_datetime(df["Timestamp"])_

Thus, given recent updates to Pandas, some code in pywaterinfo is getting outdated.

### What I Did

I used pywaterinfo in a rather generic way. Given that the issue at hand is related to the application of Pandas within pywaterinfo, getting into more detail will not give much more information.

**Comment by stijnvanhoey** [comment]
Thanks a lot for reporting, we'll try to update the `to_datetime` conversion in the code, you are also welcome to add a PR. 

If possible, can you share the time range or period you requested dat for as this might be useful for debugging the situation mentioned in the warning '_parsing datetimes with mixed time zones_'.

**Comment by Jornvdv** [comment]
I requested data from 2013-10-01 00:00:00 until 2015-06-30 23:00:00, which includes a few DST changes, which might be the cause. If I find the time, I might indeed look into it myself.

**Comment by Jornvdv** [comment]
With this code fragment, I could reproduce the FutureWarning: 

```
vmm=Waterinfo("vmm")

content = vmm.get_timeseries_values('69928042', start='2013-10-01 00:00:00', end='2015-06-30 23:00:00', timezone='CET')
```

**Comment by stijnvanhoey** [comment]
Thanks, the addition of a timezone parameters clarified the issue. See https://github.com/fluves/pywaterinfo/pull/68 for a PR. I used your use case as unit test.

**Comment by stijnvanhoey** [comment]
Fixed by https://github.com/fluves/pywaterinfo/pull/68, closing this issue. Feel free to reopen if issue still pops up.
